-- DEVELOPER.PESSOA_ORIGEM definition

CREATE TABLE "DEVELOPER"."PESSOA_ORIGEM"
(	"PK_PESSOA" NUMBER(*,0),
"NM_PESSOA" VARCHAR2(100),
CONSTRAINT "PESSOA_ORIGEM_PK" PRIMARY KEY ("PK_PESSOA")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS"  ENABLE
) SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "DEVELOPER"."PESSOA_ORIGEM_PK" ON "DEVELOPER"."PESSOA_ORIGEM" ("PK_PESSOA")
PCTFREE 10 INITRANS 2 MAXTRANS 255
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;

--MATRIZ
CREATE TABLE DEVELOPER.MATRIZ (
  PK_MATRIZ INTEGER,
  RAZAO_SOCIAL VARCHAR2(100),
CONSTRAINT MATRIZ_PK PRIMARY KEY (PK_MATRIZ)
);

CREATE TABLE "DEVELOPER"."SEGURADORA"
(	"PK_SEGURADORA" NUMBER(*,0),
"NM_SEGURADORA" VARCHAR2(100),
"CIDADE" VARCHAR2(100),
"ESTADO" VARCHAR2(100),
"PK_MATRIZ" NUMBER(*,0),
CONSTRAINT "SEGURADORA_PK" PRIMARY KEY ("PK_SEGURADORA")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
TABLESPACE "USERS"  ENABLE
) SEGMENT CREATION DEFERRED
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "DEVELOPER"."SEGURADORA_PK" ON "DEVELOPER"."SEGURADORA" ("PK_SEGURADORA")
PCTFREE 10 INITRANS 2 MAXTRANS 255
TABLESPACE "USERS" ;


--CORRETOR
-- DEVELOPER.CORRET_SEG_PROD definition

CREATE TABLE "DEVELOPER"."CORRET_SEG_PROD"
   (	"PK_CORRETOR" NUMBER(*,0),
	"NM_CORRETOR" VARCHAR2(100),
	"CPF_CORRETOR" VARCHAR2(100),
	"DSC_PRODUTO" VARCHAR2(100),
	"VLR_PRODUTO" NUMBER(*,0),
	"PK_SEGURADORA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON TABLE DEVELOPER.CORRET_SEG_PROD IS 'Corretor Seguradora Produto';
COMMENT ON COLUMN DEVELOPER.CORRET_SEG_PROD.DSC_PRODUTO IS 'Descricao do produto';
COMMENT ON COLUMN DEVELOPER.CORRET_SEG_PROD.VLR_PRODUTO IS 'Valor do Produto';
COMMENT ON COLUMN DEVELOPER.CORRET_SEG_PROD.PK_SEGURADORA IS 'Seguradora para qual o corretor atua';


--INSERTS
INSERT INTO DEVELOPER.MATRIZ
(PK_MATRIZ, RAZAO_SOCIAL)
VALUES(1, 'SULAMERICA SEGUROS');

INSERT INTO DEVELOPER.SEGURADORA
(PK_SEGURADORA, NM_SEGURADORA, CIDADE, ESTADO, PK_MATRIZ)
VALUES(1, 'SULAMERICA DO PARANA', 'PORECATU', 'PR', 1);

INSERT INTO DEVELOPER.SEGURADORA
(PK_SEGURADORA, NM_SEGURADORA, CIDADE, ESTADO, PK_MATRIZ)
VALUES(2, 'SULAMERICA DO PARANA2', 'LONDRINA', 'PR', 1);

INSERT INTO DEVELOPER.SEGURADORA
(PK_SEGURADORA, NM_SEGURADORA, CIDADE, ESTADO, PK_MATRIZ)
VALUES(3, 'SULAMERICA DE SAO PAULO', 'SAO PAULO', 'SP', 1);

INSERT INTO DEVELOPER.SEGURADORA
(PK_SEGURADORA, NM_SEGURADORA, CIDADE, ESTADO, PK_MATRIZ)
VALUES(4, 'SULAMERICA DE SAO PAULO2', 'JUNDIAI', 'SP', 1);

INSERT INTO DEVELOPER.SEGURADORA
(PK_SEGURADORA, NM_SEGURADORA, CIDADE, ESTADO, PK_MATRIZ)
VALUES(5, 'SULAMERICA DO RIO GRANDE DO SUL', 'CANOAS', 'RS', 1);

INSERT INTO DEVELOPER.SEGURADORA
(PK_SEGURADORA, NM_SEGURADORA, CIDADE, ESTADO, PK_MATRIZ)
VALUES(6, 'SULAMERICA DO RIO GRANDE DO SUL2', 'PORTO ALEGRE', 'RS', 1);

INSERT INTO DEVELOPER.SEGURADORA
(PK_SEGURADORA, NM_SEGURADORA, CIDADE, ESTADO, PK_MATRIZ)
VALUES(7, 'SULAMERICA DO RIO DE JANEIRO', 'SAO GONCALO', 'RJ', 1);

INSERT INTO DEVELOPER.SEGURADORA
(PK_SEGURADORA, NM_SEGURADORA, CIDADE, ESTADO, PK_MATRIZ)
VALUES(8, 'SULAMERICA DO RIO DE JANEIRO2', 'NITEROI', 'RJ', 1);

INSERT INTO DEVELOPER.CORRET_SEG_PROD
(PK_CORRETOR, NM_CORRETOR, CPF_CORRETOR, DSC_PRODUTO, VLR_PRODUTO, PK_SEGURADORA)
VALUES(1, 'JHON SNOW', '94119479056', 'MORTE POR FLECHA', 500, 1);

INSERT INTO DEVELOPER.CORRET_SEG_PROD
(PK_CORRETOR, NM_CORRETOR, CPF_CORRETOR, DSC_PRODUTO, VLR_PRODUTO, PK_SEGURADORA)
VALUES(1, 'JHON SNOW', '94119479056', 'MORTE POR PUNHAL', 300, 3);

INSERT INTO DEVELOPER.CORRET_SEG_PROD
(PK_CORRETOR, NM_CORRETOR, CPF_CORRETOR, DSC_PRODUTO, VLR_PRODUTO, PK_SEGURADORA)
VALUES(1, 'JHON SNOW', '94119479056', 'MORTE POR FOGO DE DRAGAO', 5000, 6);

INSERT INTO DEVELOPER.CORRET_SEG_PROD
(PK_CORRETOR, NM_CORRETOR, CPF_CORRETOR, DSC_PRODUTO, VLR_PRODUTO, PK_SEGURADORA)
VALUES(1, 'JHON SNOW', '94119479056', 'MORTE POR CONGELAMENTO', 1500, 7);

INSERT INTO DEVELOPER.CORRET_SEG_PROD
(PK_CORRETOR, NM_CORRETOR, CPF_CORRETOR, DSC_PRODUTO, VLR_PRODUTO, PK_SEGURADORA)
VALUES(2, 'JAMES HOWLETT LOGAN', '18693857053', 'LESAO POR MAGNETISMO', 90, 2);

INSERT INTO DEVELOPER.CORRET_SEG_PROD
(PK_CORRETOR, NM_CORRETOR, CPF_CORRETOR, DSC_PRODUTO, VLR_PRODUTO, PK_SEGURADORA)
VALUES(2, 'JAMES HOWLETT LOGAN', '18693857053', 'MORTE POR DECAPITACAO', 7000, 4);

INSERT INTO DEVELOPER.CORRET_SEG_PROD
(PK_CORRETOR, NM_CORRETOR, CPF_CORRETOR, DSC_PRODUTO, VLR_PRODUTO, PK_SEGURADORA)
VALUES(2, 'JAMES HOWLETT LOGAN', '18693857053', 'MORTE POR CONTAMINACAO DE ADAMANTIUM', 55000, 5);

INSERT INTO DEVELOPER.CORRET_SEG_PROD
(PK_CORRETOR, NM_CORRETOR, CPF_CORRETOR, DSC_PRODUTO, VLR_PRODUTO, PK_SEGURADORA)
VALUES(2, 'JAMES HOWLETT LOGAN', '18693857053', 'MORTE POR FUZILAMENTO', 3500, 8);

INSERT INTO DEVELOPER.CORRET_SEG_PROD
(PK_CORRETOR, NM_CORRETOR, CPF_CORRETOR, DSC_PRODUTO, VLR_PRODUTO, PK_SEGURADORA)
VALUES(3, 'LEIA SKYWALKER', '86965770007', 'LESAO POR SABRE DE LUZ', 190, 1);

INSERT INTO DEVELOPER.CORRET_SEG_PROD
(PK_CORRETOR, NM_CORRETOR, CPF_CORRETOR, DSC_PRODUTO, VLR_PRODUTO, PK_SEGURADORA)
VALUES(3, 'LEIA SKYWALKER', '86965770007', 'MORTE POR EXPLOSAO', 7000, 3);

INSERT INTO DEVELOPER.CORRET_SEG_PROD
(PK_CORRETOR, NM_CORRETOR, CPF_CORRETOR, DSC_PRODUTO, VLR_PRODUTO, PK_SEGURADORA)
VALUES(3, 'LEIA SKYWALKER', '86965770007', 'MORTE POR QUEDA DE NAVE', 65000, 6);

INSERT INTO DEVELOPER.CORRET_SEG_PROD
(PK_CORRETOR, NM_CORRETOR, CPF_CORRETOR, DSC_PRODUTO, VLR_PRODUTO, PK_SEGURADORA)
VALUES(3, 'LEIA SKYWALKER', '86965770007', 'MORTE POR ESTRELA DA MORTE', 350000, 8);


--  SELECT BASE ORIGEM
SELECT* FROM
CORRET_SEG_PROD INNER JOIN SEGURADORA
ON CORRET_SEG_PROD.PK_SEGURADORA = SEGURADORA.PK_SEGURADORA
INNER JOIN MATRIZ
ON MATRIZ.PK_MATRIZ = SEGURADORA.PK_MATRIZ
